name: gru_minions
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # communication libraries
  flutter_p2p_connection: #^2.0.2   path: ../flutter_p2p_connection
    git:
      url: https://github.com/jorisdeguet/flutter_p2p_connection.git
      ref: main
  mac_address: ^1.0.0
  # sound libraries
  #volume_controller: ^2.0.7
  #flutter_sound: ^9.2.13
  #audioplayers: ^5.2.0
  intl: ^0.18.1
  assets_audio_player: ^3.1.1
  flame: ^1.10.0
  json_annotation: ^4.8.0
  get: ^4.6.6
  image: ^4.1.3
  flame_tiled: ^1.19.0
  google_fonts: ^6.2.0
  stroke_text: ^0.0.2
  flame_audio: ^2.10.0
  rename: ^3.0.1
  flutter_animate: ^4.5.0
  scaled_list: ^2.0.0
  flame_splash_screen: ^0.3.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # potential use of complex messages inside a mode??
  json_serializable: ^6.7.1
  build_runner: ^2.3.3


flutter:
  uses-material-design: true
  assets:
    - assets/tiles/
    - assets/audio/
    - assets/icon/
    - assets/fonts/
    - assets/images/
    - assets/images/Other/
    - assets/images/Menu/Buttons/
    - assets/images/Menu/Levels/
    - assets/images/Terrain/
    - assets/images/Background/
    - assets/images/HUD/
    - assets/images/Items/Fruits/
    - assets/images/Items/Coins/
    - assets/images/Items/Checkpoints/Start/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Items/Checkpoints/End/
    - assets/images/Traps/Saw/
    - assets/images/Traps/Fire/
    - assets/images/Traps/Spikes/
    - assets/images/Traps/Trampoline/
    - assets/images/Main Characters/
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/Virtual Guy/
    - assets/images/Enemies/Chicken/
    - assets/images/Enemies/Mushroom/
    - assets/images/Enemies/Radish/
    - assets/images/Enemies/Rino/
    - assets/images/Enemies/Slime/
    - assets/images/Enemies/AngryPig/
    - assets/images/Enemies/Plant/
    - assets/images/Enemies/Trunk/