name: gru_minions
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # communication libraries
  flutter_p2p_connection: ^2.0.1
  mac_address: ^1.0.0
  # camera libraries
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  # sound libraries
  volume_controller: ^2.0.7
  #flutter_sound: ^9.2.13
  #audioplayers: ^5.2.0
  assets_audio_player: ^3.1.1
  flame: ^1.10.0
  #
  json_annotation: ^4.8.0
  invert_colors: ^0.0.4
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # potential use of complex messages inside a mode??
  json_serializable: ^6.7.1
  build_runner: ^2.3.3


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/piano/
    - assets/halloween/
    - assets/flame/